# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
   tag: $(Build.BuildId)

stages:
  - stage: Build
    displayName: Build Stage 
    jobs:
      - job: Build
        displayName: Build Job
        pool:
          vmImage: 'ubunt-latest'
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'custom-service-connection-for-pipeline'
            repository: 'customepipeline'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: 
              $(tag)
              $(Build.SourceVersion)
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            OverWrite: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'customepipeline'
            publishLocation: 'Container'